# Server
server.port=${PORT:8080}

# Nama Aplikasi
spring.application.name=SMART

# Database Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?ssl=true&sslmode=require
spring.datasource.username=postgres.joskjoyabspgdqgyaicw
spring.datasource.password=FathirRahman
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
